version: '3.7'
services:
    db:
        image: postgres:13
        environment:
            - POSTGRES_DB=deli
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - ./db/data/postgres:/var/lib/postgresql/data

    web:
        build: .
        environment:
            - POSTGRES_DB=deli
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password

        command: 'python3 manage.py runserver 0.0.0.0:8000'
        volumes:
            - .:/code
        tty: true
        stdin_open: true
        ports: 
            - 8000:8000
        depends_on:
            - db

