version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  build-and-test:
    machine: true
    steps: 
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      
      - run:
          name: Test
          command: docker-compose run web python manage.py test  


workflows:
  version: 2
  heroku-test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master

      - heroku/deploy-via-git:
          filters:
            branches:
              only: master
          requires:
            - build-and-test
      




