# Generated by Django 3.1.3 on 2020-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20201203_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
